# Generated by Django 5.2.17 on 2026-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='accent_colours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_backend_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_bullets',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='best_suited_for',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='bottom_hem',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='collection_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='product',
            name='colour_family',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='colour_fastness',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_size_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_size_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detergent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='dry_cleaning',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='drying',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='dye_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='eyelet_size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_blend',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_gsm',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_texture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='festival_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='first_wash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkart_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fullness_ratio_guide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='gujarat_heritage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gujarat_heritage_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handloom_or_machine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hanging_style',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='hardware_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='heading_tape_width',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='installation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ironing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='length_drop',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='lining',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='other_colour_options',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_contents',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_variants_and_prices',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packed_dimensions',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern_repeat',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern_scale',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_colour',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_seo_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='print_pattern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='print_technique',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rod_compatibility',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_social',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_available',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_finish',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='tie_back_tassel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='transparency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='washing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='website_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_per_panel',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
